// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwcBBR4_m1nrKRgXvjP3j3iwRE8FpBu4',
    appId: '1:645810350682:web:91c52e8c5cfd3290ddc663',
    messagingSenderId: '645810350682',
    projectId: 'johnlistrik-34d94',
    authDomain: 'johnlistrik-34d94.firebaseapp.com',
    storageBucket: 'johnlistrik-34d94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfwcBBR4_m1nrKRgXvjP3j3iwRE8FpBu4',
    appId: '1:877563246435:android:5318ebaed500ff4e6d8556',
    messagingSenderId: '645810350682',
    projectId: 'johnlistrik-34d94',
    storageBucket: 'johnlistrik-34d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXVeBmMbEw_UCk-6lKj4SqubeVBz7r6lQ',
    appId: '1:645810350682:ios:6f12bb5624f45c30ddc663',
    messagingSenderId: '645810350682',
    projectId: 'johnlistrik-34d94',
    storageBucket: 'johnlistrik-34d94.appspot.com',
    iosClientId:
        '645810350682-4om29mc38fjiiput8blpemcnhqprer5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXVeBmMbEw_UCk-6lKj4SqubeVBz7r6lQ',
    appId: '1:645810350682:ios:6f12bb5624f45c30ddc663',
    messagingSenderId: '645810350682',
    projectId: 'johnlistrik-34d94',
    storageBucket: 'johnlistrik-34d94.appspot.com',
    iosClientId:
        '645810350682-4om29mc38fjiiput8blpemcnhqprer5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoring',
  );
}
